name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # we define the runer 
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
        
      - name: Installer les dépendances
        run: npm install
      
      - name : Vérifier le code 
        run : npm run lint


      - name: Lancer les tests
        run: npm test